# Generated by Django 3.0.6 on 2020-06-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
