# Generated by Django 3.0.6 on 2020-06-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20200609_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='comp_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
